M48
; DRILL file {KiCad 7.0.10-1.fc39} date Wed 14 Feb 2024 10:35:42 PM CST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-02-14T22:35:42-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10-1.fc39
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C4.300
%
G90
G05
T1
X131.51Y-57.265
X131.51Y-77.765
X188.51Y-57.265
X188.51Y-77.765
T2
X190.21Y-98.765
M30
